### ISSUE TITLE
Logic about how to instruct granite to connect to a database is confusing/misleading/out of par with amber core

### ISSUE THREAD

**Issue by robacarp** [amberframework/granite-orm#107]
I've run into this issue myself but a kind passer-by in IRC was snagged on it too and so I think it needs some attention. This code [from adapter/base.cr](https://github.com/amberframework/granite-orm/blob/734cb52de88bb1861684ea0ce10cdab34dd42122/src/adapter/base.cr#L10-L28) is leading to confusion:

```crystal
  def initialize(adapter : String)
    if url = ENV["DATABASE_URL"]? || Granite::ORM.settings.database_url || replace_env_vars(settings(adapter)["database"].to_s)
      @database = DB.open(url)
    else
      raise "database url needs to be set in the config/database.yml or DATABASE_URL environment variable"
    end
  end


  DATABASE_YML = "config/database.yml"


  def settings(adapter : String)
    if File.exists?(DATABASE_YML) &&
       (yaml = YAML.parse(File.read DATABASE_YML)) &&
       (settings = yaml[adapter])
      settings
    else
      return {"database": ""}
    end
  end
```

I don't personally run my development environment in docker and the logic here requires me to have a `config/database.yml` file, presumably because `Granite::ORM.settings.database_url` isn't getting set properly? 

I believe the code relating to `config/database.yml` is legacy and can be removed.

For searchability, the error message this produces is:

```
no driver was registered for the schema "", did you maybe forget to require the database driver? (ArgumentError)
```

The quick solution to this problem is to put your database credentials in a file at `config/database.yml` and it should look something like this:

```yaml
pg:
  database: postgres://username:password@localhost:5432/database_name
```

**Comment by drujensen** [comment]
In Amber Core, when you generate a new model, scaffold or migration, an `initializer/granite.cr` will be generated that should set this.  

https://github.com/amberframework/amber/blob/master/src/amber/cli/templates/migration/granite/config/initializers/granite.cr.ecr

We left the `config/database.yml` for backward compatibility. 

Can you describe how to replicate the issue?

**Comment by robacarp** [comment]
@drujensen that explains why my cobbled and slowly upgraded app had this confusion, but not why a new install generated the error. The only details I have are in gitter/irc, starting here: https://gitter.im/amberframework/amber?at=5a4c1a8c29ec6ac311afbc01

**Comment by drujensen** [comment]
@robacarp I think we need to move this generator to the `app` instead of the `migrate`.  That way the initializer exists even if they don't generate a migration, scaffold or model.

**Comment by robacarp** [comment]
@drujensen I believe that would solve the problem and provide less potential snares for new devs as well.  👍🏻

**Comment by benbonnet** [comment]
can confirm this part is troublesome when onboarding there; `amber g model/scaffold/migration xxx` does not even the `initializer/granite.cr` advertised above (and the link leads to a 404)

Would you mind printing there +- accurately how to go over this issue as of today ? #1 result in google for "no driver was registered for the schema"
