### ISSUE TITLE
Save and Destroy should not eat exceptions

### ISSUE THREAD

**Issue by robacarp** [amberframework/granite-orm#116]
The [#save and #destroy methods](https://github.com/amberframework/granite-orm/blob/master/src/granite_orm/transactions.cr#L35-L41) contain a wide open rescue which eats any exception and prevents the stack trace from being emitted.

Does it make sense to constrain the rescue to a few types emitted by the different drivers and rescue only those, so that errors which happen elsewhere aren't swallowed?

One example which just bit me: a `before_save` method raised an exception.

**Comment by drujensen** [comment]
@robacarp yes, your right. This should probably only catch DDL exceptions and allow others to fall through.
