### ISSUE TITLE
Add new command "inspect" to inspect an existing database and create corresponding models

### ISSUE THREAD

**Issue by blankoworld** [amberframework/granite-orm#119]
I think it would be very helpful in the future to fetch an existing database schema and create corresponding models.

I saw this kind of functionnality here: https://docs.djangoproject.com/en/2.0/ref/django-admin/#inspectdb

Is that possible to have something similar for next versions?

**Comment by drujensen** [comment]
@blankoworld this would be more suited for Amber or a CLI tool.  We are looking into providing the ability to add custom generators to Amber.  This would be an awesome tool to quickly reverse any database into a set of models.

In theory, you could also build a whole scaffolding or admin application with this approach.  Just give the tool the list of tables and it will scaffold out the whole thing for you.

**Comment by blankoworld** [comment]
Yes the "inspectdb" is a really helpful tool!

By talking about Amber or a CLI tool, do you mean I need to create a ticket on another tool?

As I need this kind of tool, I will really appreciate to follow the project that will plan to add it ^_^

**Comment by drujensen** [comment]
@blankoworld yeah, so we have a CLI tool in Amber for generating code.  This would be in that code base found [here](https://github.com/amberframework/amber/tree/master/src/amber/cli)

We could add a new command, something like `amber inspectdb User Post Comment` that would connect to the database, look for these tables, inspect the fields and types, and then generate the scaffolding from them.

We are looking into allowing people to create their own shard that would extend this CLI tool to allow others to create features just like this one.

Can you move this request over to an issue in Amber instead?  It's more suited to that tool than here.

**Comment by blankoworld** [comment]
As I created a ticket on Amber about this kind of command, I close this ticket and hope someone will be interested in this kind of enhancement ^_^.

Thank you for your help to redirect me to the right place and have fun with granite-orm ;)
