### ISSUE TITLE
Granite debug output

### ISSUE THREAD

**Issue by lebogan** [amberframework/granite-orm#141]
I am writing a simple cli maintenance logger using the granite-orm, sqlite3, crystal 0.24.1 on a Fedora vagrant box. After micrating, seeding, and setting my model:
```
class Memo < Granite::ORM::Base
  adapter sqlite
  table_name memos
  field title : String
  field body : String
  field entry_date : String
end

def find_all
  memos = Memo.all
end
```
Since I'm not printing anything, I expect a blank screen. Instead I get:
```
I, [2018-02-14 10:48:56 - ...] INFO -- Granite: SELECT memos.id ......: []
```
What is printing this ,I guess, debug sql statement and can I suppress it?

Thanks for your help.

**Comment by faustinoaq** [comment]
Hi @lebogan We added Granite logs to integrate this shard with [Amber logs](https://github.com/amberframework/amber/blob/master/src/amber/cli/templates/app/config/initializers/database.cr.ecr#L5)

Try this:

```crystal
Granite::ORM.settings.logger = Logger.new(nil)
```

See: https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Crystal/amber/config/initializers/database.cr#L3

**Comment by lebogan** [comment]
That worked. Thank you.
