### ISSUE TITLE
Inserting row using MySQL and custom primary key

### ISSUE THREAD

**Issue by Blacksmoke16** [amberframework/granite-orm#155]
I am encountering an issue where I cannot insert a new record into a table using a custom primary key.

Model
```
class Alliance < Granite::ORM::Base
  adapter mysql
  primary alliance_id : Int64
  field alliance_name : String
end
```

MySQL Table
```
CREATE TABLE alliances
(
  alliance_id   BIGINT NOT NULL PRIMARY KEY,
  alliance_name VARCHAR(255) NOT NULL
)
```

Query
```
alli = Alliance.new
alli.alliance_id = 9999
alli.alliance_name = "Joe"
alli.save
```

When executing this query i get this error:
```
Error in sde.cr:27: no overload matches 'Alliance#alliance_id=' with type Int32
Overloads are:
 - Alliance#alliance_id=(alliance_id : Union(Int64 | Nil))

alli.alliance_id = 99002938
     ^~~~~~~~~~~
```

If i change the model type to Int32 the query runs but does an update instead, which does nothing.
```
I, [2018-03-09 20:04:10 -05:00 #3826]  INFO -- Granite: UPDATE alliances SET alliance_name=? WHERE alliance_id=?: ["DARKNESS.", 99002938]
```

**Comment by robacarp** [comment]
To get around the `with type Int32`, you can specify your id as `9999_i64`.

However, right now the implementation in Granite decides if the query should be an update or an insert by [evaluating the primary key](https://github.com/amberframework/granite-orm/blob/master/src/granite_orm/transactions.cr#L17) for nilness, making natural keys incompatible with the current implementation.

**Comment by Blacksmoke16** [comment]
I'll give that a try thanks.

**Comment by Blacksmoke16** [comment]
That worked thanks!
```
item = Item.new(type_name: "Rhea")
item.type_id = 9999_i64
item.save
```

However it seems #143 would be very helpful to do the create statement in one line, versus having to set the primary key separately.
