### ISSUE TITLE
Database defined NOT NULL + DEFAULT value

### ISSUE THREAD

**Issue by danielwestendorf** [amberframework/granite-orm#157]
I'm trying to create a column which is a database generated UUID default value, however, I can't seem to get this working.

What I expect to happen is that when I create a record without specifying a value for the column in question. After the record is saved the the column in question will have a UUID value.

```sql
-- +micrate Up
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE accounts (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR,
  api_key uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);


-- +micrate Down
DROP TABLE IF EXISTS accounts;
```

```ruby
class Account < Granite::ORM::Base
  adapter pg
  table_name accounts

  field name : String
  field api_key : String
  timestamps
end
```

```ruby
account = Account.new(name: 'Bob')
account.save # => INSERT INTO accounts (name, api_key, created_at, updated_at) VALUES ($1, $2, $3, $4): ["Bob", nil, "2018-03-09 19:50:44", "2018-03-09 19:50:44"]
```

This results in `null value in column "api_key" violates not-null constraint`.

How do I get Granite to support default db values?

**Comment by drujensen** [comment]
#166 Supporting Natural Keys allows you to disable auto incrementing.  This will allow you to set your own key.
