### ISSUE TITLE
add support for 1 to many relationships

### ISSUE THREAD

**Issue by drujensen** [amberframework/granite-orm#30]
Create two new macros: `belongs_to` and `has_many`

```crystal
require "./post"

class Comment < Kemalyst::Model
  belongs_to post
  ...
end
```
This will create a mapping to the `post_id : Int64` field and generate a method that will query the parent and return it.

```
def post
  Post.find post_id
end
```

```crystal
require "./comment"

class Post < Kemalyst::Model
  has_many comments
  ...
end
```
This will create a method called comments that will query the children records.
```
def comments
  Comments.all("JOIN posts ON posts.id = comments.post_id WHERE posts.id = ?", id)
end
```
Options to override the field names and types should be considered for legacy database mappings.

One of the difficulties is requiring the other model.  Macros do not allow you to inject `require` into the class.

Another issue is the N+1 queries for comments.  I think we can find ways of optimizing this later.

**Comment by elorest** [comment]
I would suggest that all of the models should be loaded into the main project file.

```cr
#src/blog.cr
require "./models/*"
```

**Comment by drujensen** [comment]
can you require all subdirectories as well?  does this work in crystal? `require "./models/**/*`

**Comment by drujensen** [comment]
found it:  https://crystal-lang.org/docs/syntax_and_semantics/requiring_files.html
```crystal
require "./models/**"
```

**Comment by elorest** [comment]
Both of those will work. For instance `require "./**/*"`

**Comment by azah** [comment]
I'll try and take a stab at this in the next few weeks.

**Comment by migeorge** [comment]
Closing since #52 was merged.
