### ISSUE TITLE
Can't insert model with Time value using mysql adapter

### ISSUE THREAD

**Issue by MSDandrea** [amberframework/granite-orm#44]
I have the following table:
```sql
CREATE TABLE if NOT EXISTS tokens(
  id BIGINT NOT NULL AUTO_INCREMENT,
  permission BIGINT NOT NULL,
  expires_at TIMESTAMP,
  ttl INT,
  created_at TIMESTAMP,
  updated_at timestamp DEFAULT current_timestamp() ,
  primary key(id),
  FOREIGN KEY (permission)
    REFERENCES permissions(id)
);
```

and I used the following model to represent it:
```crystal
require "granite_orm/adapter/mysql"

class Token < Granite::ORM
  adapter mysql
  field permission : Int64
  field expires_at : Time
  field ttl : Int32
  timestamps
end
```

using this code:
```crystal
require "./models/*"

token = Token.new

token.permission = Int64.new(11)
token.ttl = 41
token.expires_at = Time.now
token.save
```
I receive this error: `Save Exception: Incorrect datetime value: '' for column 'expires_at' at row 1`

I investigated a little and the statement and params passed to mysql are:
`INSERT INTO tokens (permission,expires_at,ttl,created_at,updated_at) VALUES (?,?,?,?,?)`
`[11, 2017-08-13 20:54:06 -0300, 41, "2017-08-13 20:54:06", "2017-08-13 20:54:06"]`

It seems  that the second params value should be `expires_at.to_s("%F %X")` in order to be accepted by mysql (as both as created_at and updated_at)

I tried to solve the issue and submit a PR but my knowlodge in crystal macros are not that good yet.
Thanks.

**Comment by migeorge** [comment]
Closing this since #45 was merged.
