### ISSUE TITLE
Modulize Granite::ORM

### ISSUE THREAD

**Issue by c910335** [amberframework/granite-orm#49]
I think it is time to modulize Granite::ORM because `src/granite_orm.cr` is too complicated to add new features.
The following are my suggestions.

#### Renaming `Granite::ORM` to `Granite::ORM::Base`

If we want to split `Granite::ORM` into modules, those modules should be inside a module which is very likely to be named as `Granite::ORM`. Thus, renaming the original class `Granite::ORM` to `Granite::ORM::Base` is necessary although it is a breaking change.

#### The Plan for Modulizing

- src
  - adapter - unchanged
  - granite_orm
    - associations.cr - things mentioned in this issue #30 
    - base.cr - require all the other files in `src/granite_orm`, declare class `Granite::ORM::Base`, include(extend) the modules and constructors
    - callbacks.cr - things in my previous pr #42 
    - fields.cr - macro `field`, `timestamps`, `process_fields` (but this is still too large and need partitioning), and method `set_attributes`
    - querying.cr - current public class methods
    - table.cr - macro `adapter`, `table_name`, `primary`
    - transactions.cr - method `save`, `destroy`
    - version.cr - just version
  - granite_orm.cr - `require "./granite_orm/base"`

There may be some difficulties and this plan still needs improvements, so let's start discussing.

**Comment by drujensen** [comment]
@c910335 yes, I agree long overdue.  I like your proposal.  

We are also looking to move Kemalyst::Validators into Granite::ORM so this modularization would be a welcome change.

Is this something you will be working on?

**Comment by c910335** [comment]
If there is no progress by now, I am going to deal with this.

**Comment by drujensen** [comment]
I"m not aware of anyone working on this.  thanks @c910335

**Comment by c910335** [comment]
Why are there so many class methods defined in the macro `process_fields`?
I think `clear`, `all`, `find`, `find_by`, `exec`, `query` and `scalar` should be taken out of it because they didn't access any macro variables.

**Comment by drujensen** [comment]
This is remnants from before having the ability to do a `finished` macro.  https://github.com/amber-crystal/granite-orm/blob/master/src/granite_orm.cr#L15

If we can remove them from the macro now, we should.

**Comment by c910335** [comment]
Forgot associations.cr
