### ISSUE TITLE
Add support for to_json to models

### ISSUE THREAD

**Issue by migeorge** [amberframework/granite-orm#50]
When developing an API only application with Amber the need for JSON model serialization becomes apparent rather quickly.

It seems logical to add JSON mapping support to Granite models so I wanted to open this issue to start a discussion.

I'm willing to put some time towards a PR on this, but I wanted to get input from existing members of this project to flesh out an acceptable implementation before putting the effort into actually developing the solution.

Questions:

1. Should Granite::ORM implement a to_json method on models similar to the `JSON.mapping` macro?
2. Should Granite::ORM implement a JSON -> Model interface similar to the `JSON.mapping` macro?
3. Is there a good way to inherit some of this functionality (from Crystal core) without re-implementing it?

**Comment by drujensen** [comment]
Hi Mike.

Thanks for opening the discussion. 

I have put a lot of thought into this over the years and have tried implementing a clean JSON mapping in granite ORM to no avail. 

The current JSON.mapping in the core requires an initializer that conflicts the granite initilizer. 

Also, To properly serialize to JSON, most users will need to map to customized key names.  In the JS world, they will want the keys to be camelCased. 

I have leaned toward writing Serializers in my own projects that take the model as an init parameter and perform the mapping with a hash. This is a great place to add other methods that can handle other mapping logic. 

However, if we did pursue adding a to_json mapping, One of the best options I have attempted is allowing for more parameters to be specified in the mapping including a key name for the JSON mapping. 



...

**Comment by migeorge** [comment]
That makes sense for a simple API it might make sense to stick with `to_json` so you can return something like the following in your controller:

```
{ users: User.all }.to_json
```

But I do also see the case for Serializers. Often times in rails projects I find myself reaching for Active Model Serializers, especially once you get into side-loading relationships. Maybe Granite models could support `to_json` and we also add an optional serialization library to the Amber ecosystem. If the models support `to_json` it would probably also simplify the implementation of the serialization library.

I also like the implementation proposal you have. It would also be nice for it to infer the type of the field so the explicit configuration of the field could be optional.

As far as the timestamps go, it may be sane to exclude them from the json payload by default and add an argument to the macro to toggle settings like `{ json: { include: true, camelCase: true } }`

**Comment by elorest** [comment]
My thoughts are that we should just return a Hash(Symbol, String) we could call to_json on it or pass it to another serializer. That way we easily allow for extendability without having to build a serializer in or really changing the system at all. Thoughts?

**Comment by drujensen** [comment]
@elorest that should be fairly straight forward to do in the mapping macro and they can override the `to_json` method or create a serializer if they need more than what it can provide.

**Comment by villzor** [comment]
Connecting to my other suggestion regarding relationships (https://github.com/amberframework/granite-orm/issues/59), I started sketching on overriding the to_json(json : JSON::Builder) functionality, and adding support for mapping relationships as well. I haven't considered the possibility of adding custom naming of fields with camelcase and so forth, but by overriding this function we can to_json on both the object itself and an array of it, e.g. Array(Recipe).to_json as each object would call the inner to_json function. This produces these results:
```
rec = Recipe.find_by({:recipe_id => 1})
puts rec.to_pretty_json
```
Output:
```
{
  "recipe_id": 1,
  "title": "Morotssoppa",
  "created_at": "2017-09-02 13:05:52 +0200",
  "updated_at": "2017-09-02 13:05:52 +0200",
  "ingredients": [
    {
      "amount": 5,
      "ingredient": {
        "ingredient_id": 3,
        "name": "morot",
        "created_at": "2017-07-30 12:55:35 +0200",
        "updated_at": "2017-07-30 12:55:35 +0200"
      },
      "unit": {
        "unit_id": 2,
        "name": "stycken",
        "short_name": "st",
        "unit_type": 0,
        "unit_amount": 1,
        "is_default": true,
        "created_at": "2017-07-31 11:28:53 +0200",
        "updated_at": "2017-07-31 23:06:25 +0200"
      }
    },
    {
      "amount": 300,
      "ingredient": {
        "ingredient_id": 2,
        "name": "potatis",
        "created_at": "2017-07-30 12:55:27 +0200",
        "updated_at": "2017-07-30 12:55:27 +0200"
      },
      "unit": {
        "unit_id": 1,
        "name": "gram",
        "short_name": "gr",
        "unit_type": 1,
        "unit_amount": 1,
        "is_default": true,
        "created_at": "2017-07-31 11:28:42 +0200",
        "updated_at": "2017-07-31 11:28:42 +0200"
      }
    }
  ],
  "steps": [
    {
      "recipe_id": 1,
      "step_order": 1,
      "description": "Hacka morot.",
      "created_at": "2017-09-09 15:35:20 +0200",
      "updated_at": "2017-09-09 15:35:20 +0200"
    },
    {
      "recipe_id": 1,
      "step_order": 2,
      "description": "Hacka potatis.",
      "created_at": "2017-09-09 15:35:26 +0200",
      "updated_at": "2017-09-09 15:35:26 +0200"
    },
    {
      "recipe_id": 1,
      "step_order": 3,
      "description": "Hacka koka grytan.",
      "created_at": "2017-09-09 15:35:38 +0200",
      "updated_at": "2017-09-09 15:35:38 +0200"
    }
  ]
}
```
Haven't considered camelcase though, so I can be of no help there!

**Comment by drujensen** [comment]
@elorest I like your proposal.  We provide a `to_h` method in the model instead.

This will allow you to do a filter/merge/map or other manipulations and then call `to_json` on the hash to deliver it.

For example, to deliver CamelCase, you can do something like this:
```
user = User.find 1
user.to_h.map{|key, value| [key.camelcase, value] }.to_h.to_json
```

**Comment by migeorge** [comment]
:+1:

I like that as well now that I think about it. If we want to provide a serialization layer for Amber at some point it should be a separate package.

I can work on this when I have some free time unless someone else wants to pick it up

**Comment by drujensen** [comment]
Thanks @migeorge.  If you want to pair on it, let me know.

**Comment by drujensen** [comment]
while we are at it, we can add a convenience method `to_json`:
```crystal
def to_json
  to_h.to_json
end
```

**Comment by ansarizafar** [comment]
Named tuple in the field macro is a better option.

**Comment by drujensen** [comment]
@ansarizafar Care to elaborate? Why is it a better option?

My argument against a named tuple in the field macro is that the field macro will be doing too much stuff.  Not only will it be a mapping for how you map to the database, it will be a mapping on how you serialize.  I'm convinced this is a bad design since it brakes the S in SOLID.

Let us know what your arguments are for using a named tuple.
