### ISSUE TITLE
Provide field! for property!

### ISSUE THREAD

**Issue by c910335** [amberframework/granite-orm#57]
Most of the times, we are very sure that a field is not nil (by validator, default value or SQL not null constraint), so it is annoying to check nil every time and [property!](https://crystal-lang.org/api/0.23.1/Object.html#property%21%28%2Anames%29-macro) works well for this situation.

**Comment by drujensen** [comment]
nice!  I love seeing the language grow.  We used to always use `not_nil!` which is super annoying.

**Comment by faustinoaq** [comment]
Is this issue already fixed?

**Comment by drujensen** [comment]
Yes, they are.  closing this issue.  Thanks @faustinoaq.
