### ISSUE TITLE
Improving relationships between models 

### ISSUE THREAD

**Issue by villzor** [amberframework/granite-orm#59]
When using Granite-Orm I found myself missing a lot of functionalities in terms of relationships between models, and after starting extending it in my own chamber I wanted to share some thoughts on improvement, my approach so far and possibilities to contribute this to Granite. I'm still a beginner in Crystal so I'm sorry if some of my code is written poorly!

## Distinguishing between serial and primary
By distinquishing between serial (an autoincrementing field in DB) from primary(a primary key, not incrementing), it opens up better possibilities to start mapping many-to-many relationships through joining tables, in the same manner as before, and could be added as: 
`macro serial(col)
    {% SERIAL[col.var] = col.type %}
  end`

## Identiying the most important database relationships to cover
For Granite to mirror the different kind of relationships found in databases, I created the following cases and cover them one by one below:

1. many
2. many_through
3. many_tuples_through
4. one 
5. one_tuple

I've been working on a website for creating recipes with object references for ingredients, so I will use my recipe structure to exemplify the different cases.

### 1. many
This is what is called "has_many" in Granite today, a one-to-many relationship. Basically, a recipe has many steps, and each step has a primary key which links it to the specific recipe.
```
class Recipe < Model
  serial recipe_id : Int32
  field title : String
  include_timestamps
  has_many steps : Step
end

class Step < Model
  primary recipe_id : Int32
  primary step_order : Int32
  field description : String
  include_timestamps
end
```

The steps are lazily loaded within the Model, such as:
```
{% for name, type in MANY %}
      property {{name.id}} : Array({{type.id}}) { {{type.id}}.where({ 
      {% for name, type in SERIAL %}
            :{{name.id}} => @{{name.id}}, {% end %}
      {% for name, type in PRIMARY %} ::{{name.id}} => @{{name.id}}, {% end %} }) }
{% end %}
```
### 2. many_through
This is the standard many-to-many case, where two tables are joined through a joining table. Besides poor naming of my functions, here is a sketch how the adapter part of the function would behave:
```
def many_through(parent, child, joiner)
    statement = String.build do |stmt|
      stmt << "SELECT "
      stmt << child.property_names.map { |key| 
          "#{child.table}.#{key}" 
        }.join(", ") 
      stmt << " FROM "
      stmt << joiner.table
        stmt << " INNER JOIN " + child.table + " ON "
        stmt << child.keys.map { |key| 
          "#{child.table}.#{key} = #{joiner.table}.#{key}"
        }.join(" ")
      stmt << " WHERE "
      stmt << parent.class.keys.map_with_index { |key, index| "#{joiner.table}.#{key} = $#{index + 1}"}.join(" AND ")
    end
    open do |db|
      db.query statement, parent.keys do |rs|
        yield rs
      end
    end 
  end
```
This allows the following syntax:
```
class Ingredient < Model
  serial ingredient_id : Int32
  field name : String
  include_timestamps
  has_many pesticides : Pesticide, {:through => IngredientPesticide}
end
```
In the same manner, these are lazily loaded with the Ingredient through the Model.
### 3. many_tuples_through
This covers the case of more complex joining through multiple tables, also including the possibility to add fields (on top of primary keys) to the joining table. For instance, a recipe consists of ingredients. In the database, we have tables for ingredients and units which are pointed at by the recipe. The actual ingredient is a joining table consisting of (bold indicates PK):
**recipe_id, ingredient_id, unit_id**, amount
These are then mapped through a joining query, such as: 
```
  def many_tuples_through(parent, children, joiner)
    statement = String.build do |stmt|
      stmt << "SELECT "
      stmt << children.map { |name, child| 
        if child.responds_to?(:property_names)
          child.property_names.map { |prop| "#{child.table}.#{prop}" }.join(", ")
        else
          "#{joiner.table}.#{name}"
        end 
      }.join(", ")
      stmt << " FROM "
      stmt << joiner.table 
      children.map { |name, child|
        if child.responds_to?(:table)
          stmt << " INNER JOIN " + child.table + " ON "
          stmt << child.keys.map { |prop| 
            "#{child.table}.#{prop} = #{joiner.table}.#{prop}"
          }.join(" ")
        end
      }.join(" ")
      stmt << " WHERE "
      stmt << parent.class.keys.map_with_index { |key, index| "#{joiner.table}.#{key} = $#{index + 1}" }.join(" AND ")
    end 
    open do |db|
      db.query statement, parent.keys do |rs|
        yield rs 
      end
    end
  end
```
This then generates the following SQL in our case:
```
SELECT recipe_ingredient_unit.amount, ingredients.ingredient_id, ingredients.name, ingredients.created_at, ingredients.updated_at, units.unit_id, units.name, units.short_name, units.unit_type, units.unit_amount, units.is_default, units.created_at, units.updated_at 
FROM recipe_ingredient_unit 
INNER JOIN ingredients ON ingredients.ingredient_id = recipe_ingredient_unit.ingredient_id 
INNER JOIN units ON units.unit_id = recipe_ingredient_unit.unit_id 
WHERE recipe_ingredient_unit.recipe_id = $1
```
This means we can have these 4 tables: recipes, ingredients, units and recipe_ingredient_unit. My model then allows for the following syntax: 
```
class Recipe < Model
  serial recipe_id : Int32
  field title : String
  include_timestamps
  has_many steps : Step
  has_many_tuples ingredients : {amount: Int32, ingredient: Ingredient, unit: Unit}, {:through => RecipeIngredientUnit}
end
```
This declaration instansiates an array of namedtuples consisting the fields in the joining table (in this case amount), and the objects in the other tables, also lazily loaded. 

### 4. one 
Same as belongs_to today.
### 5. one_tuple
A combination of many_tuples_through and one, e.g 
```
class Nutrition
has_one recommended_daily_dosage : {rdi: RDI, unit: Unit}
end
```
I thought this was way too big to be considered a pull request so I added it as an issue and perhaps find someone interested in helping me improve upon it so it can be viable for Granite! :) 
Also, thanks for the great work on Granite, I hope I can be of some help contributing!

**Comment by drujensen** [comment]
Hi @villzor Thanks for opening an issue for discussion.  I'm glad you are using Granite and the feedback is critical for it's success.

1. Many to Many relationships

In my experience, when making a many to many relationship, it is best to create one to many relationships to a new model that represents the relationship.  For example, lets say you have a many to many relationship between users and rooms.  Instead of creating a table and using `serial` or `primary` as you are recommending, you would create a new model that represents the relationship called `participants`.  This new model would have an `id` that is auto-incremented avoiding the need for `serial` macro.  Also, this model at some point may hold data that is relevant the the relationship like a status field.

I haven't encountered a case where having a hidden many-to-many table is a better approach and I have used this design pattern for many years.

However, what would be very useful in Granite is a `through:` clause on the `has_many` relationship.

For example:
```
class User
  has_many :participants
  has_many :rooms, through: :participants
end

class Participants
  belongs_to :user
  belongs_to :room
end

class Room
  has_many :participants
  has_many :users, through: :participants
end
```

Let me know your thoughts on this.  Each table is represented as a model so this will remove the need for a `serial` vs `primary` macro.

2. Has many tuples and Has one tuple

When I first built Kemalyst-Model (several years ago), I had the concept of a Read Only Model. This is a model that would map any SQL statement results to a class. Unfortunately, after many changes in Crystal including common DB adapters, this concept was dropped.

This is similar to your Tuple idea but instead of untyped fields, a Read Only Model would provide a mapping to typed fields giving you better integration with views for reporting needs.

Let me know your thoughts on this concept and if you think it would have improved your experience using Granite.

**Comment by villzor** [comment]
Thanks for your swift response! Yes, I agree that the syntax for many to many relationships you provided is much more aligned with how Granite is designed today and it is probably the better choice. Redeveloping my ideas to add the through: clause would be more sensible. I'm not entirely sure how you envision designing the database structure of the participant class with the auto-incrementing id? If I wanted to query this database and find all rooms where User 1 is a participant, what would be the underlying query? 

If we return to the database structure with Recipe, Ingredient, Unit and Amount, e.g. field values on joining tables and multiple foreign keys to different tables, how would this be mapped in Granite? I'm not sure if I'm understanding the Read Only Model correctly?
```
class Ingredient
  # ??
end

class Unit
  # ??
end

class RecipeComponent
  belongs_to :ingredient
  belongs_to :unit
  belongs_to :recipe
  field amount : Int32 # ??
end

class Recipe
  has_many :recipecomponents
  has_many {:ingredients, :units}, through: recipecomponents # ??
end
```
As the unit class consists of methods for conversion between different measures such as how to convert 100 grams of flour to x deciliters of flour I don't see how to structure the backend differently, as the amount field is not native to either the ingredient, recipe or unit class. 

No matter the means, I would like to achieve the end goal as following:
```
rec = Recipe.find_by :recipe_id, 1
rec.recipecomponents.each do |component|
  component.ingredient
  component.unit
  component.amount
end 
```

**Comment by drujensen** [comment]
The migration script for the `participants` table would look like this:
```
-- +micrate Up
CREATE TABLE participants (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  room_id BIGINT NOT NULL,
  created_at TIMESTAMP NULL,
  updated_at TIMESTAMP NULL
);

CREATE INDEX user_id_idx ON participants (user_id);
CREATE INDEX room_id_idx ON participants (user_id);

-- +micrate Down
DROP TABLE IF EXISTS participants;
```
The naming conventions follows the rails approach for one to many relationships.

The query to find all the rooms where user_id: 1 is a participant would be:
```
SELECT room.* FROM rooms 
JOIN participants p ON p.room_id = room.id
WHERE p.user_id = 1
```

**Comment by drujensen** [comment]
Regarding your recipe example, you are correct;  It would not need a Read Only Model which I was proposing.  We could leverage the `through:` clause to get all the ingredients and units for a recipe through the recipe components table and your final example will work.

btw, if you wanted a reverse mapping to find out all the recipes that has a certain ingredient:
```
class Ingredient
  has_many :recipecomponents
  has_many :recipes, through: :recipecomponents
end
```

Then you can do something like this:
```
ingredient = Ingredient.find_by name: "thyme"
ingredient.recipes.each do |recipe|
  puts recipe.name
end
```

**Comment by villzor** [comment]
That would be excellent!

I don't think I'm experienced enough to contribute with this feature, but let me know if I can help out developing some part of it. Really excited to see Granite evolving, it adds a a lot to the Crystal language at large!

**Comment by faustinoaq** [comment]
Wow, excellent comments, I learnt a lot reading you 👍

**Comment by drujensen** [comment]
@villzor #63 added support for the `has_many through:` based on this discussion.  Thanks again for opening this issue and using Granite.

**Comment by villzor** [comment]
Sorry for this late feedback, I missed your comment. I just noticed how this got added to my project when I upgraded my shards, great work and thanks!
