### ISSUE TITLE
Undefined constant Text

### ISSUE THREAD

**Issue by darkwinternight** [amberframework/granite-orm#60]
I'm new to Crystal and Granite but when trying the example code, I get:

```
expanding macro
in macro 'property' expanded macro: macro_4515426128:567, line 4:

   1.
   2.
   3.
>  4.             @message : Union(Text | Nil)
   5.
   6.             def message : Union(Text | Nil)
   7.               @message
   8.             end
   9.
  10.             def message=(@message : Union(Text | Nil))
  11.             end
  12.
  13.
  14.
  15.

undefined constant Text
```

I simply created a model with 

```crystal
field message : Text
```

**Comment by c910335** [comment]
You should use `String` instead of `Text`.

```cr
field message : String
```

**Comment by darkwinternight** [comment]
Thank you! I did that and it is working. However, then the `README` should be changed :)

**Comment by drujensen** [comment]
@darkwinternight you can use `text` if you also used `TEXT` as your database field. 

We should probably document the mapping between Crystal and Mysql fields.

You can find them in the Amber generator templates here:  

https://github.com/amberframework/amber/blob/master/src/amber/cli/templates/field.cr#L3

**Comment by drujensen** [comment]
nm, i take that back.  Your correct, the mapping is still String -> TEXT.  I will update the readme.  thanks for pointing that out.

**Comment by darkwinternight** [comment]
Thank you! 😄 

By the way, it's a great package! It got me started real quick with my first Crystal project!
