### ISSUE TITLE
How to create tables

### ISSUE THREAD

**Issue by mayankjohri** [amberframework/granite-orm#69]
I am not sure about how to create tables using granite-orm and was not able to find the documentation for it.
my code below is producing error: Save Exception: no such table: abc

```crystal
class Abc < Granite::ORM::Base
  adapter sqlite
  table_name abc
  field name : String
end 

a = Abc.new 
a.name = "test"
a.save
```
Error Message:
Save Exception: no such table: abc
---------------------

**Comment by danielwestendorf** [comment]
It’s in the wiki, see here https://github.com/amberframework/granite-orm/wiki/Migrations-with-micrate

**Comment by mayankjohri** [comment]
Thanks a lot
