### ISSUE TITLE
Unclear how to do password hashing

### ISSUE THREAD

**Issue by Qard** [amberframework/granite-orm#80]
I'm trying to create a user model which I can do something like `User.new({ email: "me@example.com", password: "password" })` and have it transform the "password" input field to a "hash" field in the db that has the hashed password. It's unclear to me exactly how to achieve this with granite.

It seems `User.new(...)` and `user.set_attributes(...)` only accepts values explicitly named with `field`, so I'd have to use the same `hash` name as what is in the database. I looked at using the `before_save` callback, but I'm not sure how to tell if the value is new or already hashed.

It'd also be nice to have some way for fields like this to only be accessible from within the model, that way you'd have to explicitly write functions to interact with them. Like the `hash` field should really only ever be readable in a `login` method.

Any ideas?

**Comment by drujensen** [comment]
Hi @Qard 

Take a look at this guide in Amber. https://amberframework.org/guides#recipes/examples/amber-auth-example.md

Let me know if this example is what you are looking for or if you were trying to do something different.

**Comment by Qard** [comment]
Ah, yep. That's just what I was looking for. Should probably include that in the docs for granite itself though. 👍 

Still would be neat to have a way to exclude certain fields from being externally available. Nothing stopping the `encrypted_password` field from being read outside of the model.
