### ISSUE TITLE
Simple localized fields implementation

### ISSUE THREAD

**Issue by infernalmaster** [amberframework/granite-orm#98]
So I have:

```
class Article < Granite::ORM::Base
....
  field title_en : String
  field title_it : String

  # if it was ruby I could implement it like this
  def title
    self.send("title#{I18n.locale}")
  end
end
```

Can it be implemented in crystal like macros maybe? If "yes", can someone help me with that?

**Comment by drujensen** [comment]
hi @infernalmaster  This may be possible with macros but have you considered a slightly different approach of using rows instead of columns to store different languages?
```
class Article < Granite::ORM::Base
  belongs_to :language

  primary id : Int64
  field language_id : Int64
  field title : String
end

class Language < Granite::ORM::Base
  primary id : Int64
  name : String
end
```

Your queries would need to include a filter on the `language` but this approach would allow you to add new languages without modifying the schema down the road.

**Comment by drujensen** [comment]
If you are using standardized i18n language codes i.e. `en`, `it`, you could drop the second model for language and just filter for those instead.

**Comment by faustinoaq** [comment]
Hi @infernalmaster We have't implemented internationalization yet, but I think you can't use macros for that

Unless locale is available at compile time, so you could so something like:  

```crystal
class Article < Granite::ORM::Base
  field title_en : String
  field title_it : String

  macro title_locale
    title_{{I18n.locale.id}}
  end

  def title
    title_locale    
  end
end
```

But `I18n.locale` is runtime,  right?

So I think you can use something like:

```crystal
class Article < Granite::ORM::Base
  field title_en : String
  field title_it : String

  # Try using case statement
  def title
    case I18n.locale
    when "en" then title_en
    when "it" then title_it
    end
  end
end
```

**Comment by infernalmaster** [comment]
Hi. Thank you guys for quick response.

@drujensen Nice approach, I think it will cover my needs.

@faustinoaq Yes, `I18n.locale` is runtime variable. `case statement` isn't very flexile, but can be good solution for small project. And I looked at other ORMs and found at docs (https://github.com/imdrasil/jennifer.cr/blob/master/docs/model_mapping.md) of `jennifer.cr` that they have:

method     | args                    | description
#attribute | String | Symbol | returns attribute value by it's name

I didn't try it but maybe granite-orm has something similar?

**Comment by drujensen** [comment]
@infernalmaster No, granite does not have an `attribute` method which is an interesting fix for this problem.  I'm wondering if it would bypass the property get and set methods?

**Comment by infernalmaster** [comment]
I'm new to crystal and investigating about infrastructure if it can replace rails for my task. So I'm doing pet project to find it out. You helped me alot, so you can close this issue. Thank you guys.

**Comment by drujensen** [comment]
@infernalmaster Thanks for your feedback.  One of our goals is to make the transition from Rails to Amber as seamless as possible.  I'm glad to hear you are working on a pet project.  I hope the transition is not too difficult.  Let us know if you run into anything else that you find difficult.
