### ISSUE TITLE
Catch type-casting errors in set_attributes to append to errors

### ISSUE THREAD

**Issue by opiation** [amberframework/granite-orm#99]
Currently in `set_attributes`, casting errors simply bubble up making errors potentially ambiguous when creating records with a param hash.

```crystal
class Post < Granite::ORM::Base
  field likes : Int32
end

p = Post.new({ "likes" => "" })
```

Results in:
```
Invalid Int32:
```

These errors are not stored in p.errors as this happens before `#valid?` is called.  This means that Post hashes provided to create a new Post must be validated before being sent to Post.new.

Perhaps, `cast_to_field` could rescue type casting errors and append the type error message to `p.errors` including the field name.  This would allow some core validation to remain in Granite rather than also having it in each model or in controllers.

**Comment by drujensen** [comment]
@opiation This is an excellent point.  Also, save should call validate and return an error or a boolean when it fails now that validation is integrated with granite.

**Comment by drujensen** [comment]
@opiation Is this something you would like to work on?  if not, @amberframework/granite-orm-contributors anyone want to work on this?

**Comment by opiation** [comment]
I believe having `Granite::ORM::Base#save` validate and return a boolean or error would indeed make Granite a little more ActiveRecord-like, though that seems already tracked separately in #81.

As for wanting to work on this, I'll review the contribution guide and my schedule.  In that time however, I welcome anyone to take on the task as I may not have much time in the near future.
